"""empty message

Revision ID: e1d21ed3c791
Revises: d0c5bab9afea
Create Date: 2024-04-08 21:27:15.540484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1d21ed3c791'
down_revision = 'd0c5bab9afea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.DECIMAL(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.DECIMAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
